Add cluster definition to CONTRIBUTING.md
alex-spies/elasticsearch pull request #2
Opened 2023-12-04 10:54 UTC by alex-spies

Our contribution instructions do a good job of quickly explaining how to start a local test cluster.

I think it's useful for new contributors to be find the cluster definition quickly as well. Currently, this requires a good amount of `rgrep`ing.

Additionally, I think devs often like to disable auth when working on a local cluster; why don't we give this setting more visibility :)

2023-12-04 11:03 UTC, breskeby requested changes
Adding one suggestion

2023-12-04 11:03 UTC, breskeby commented on CONTRIBUTING.md
> +The definition of this Elasticsearch instance can be found [here](build-tools-internal/src/main/groovy/elasticsearch.run.gradle).
You might want to reference the username/password ('elastic-admin'/'elastic-password') here directly as almost  everyone would need that anyhow and only point to the cluster definition for further details of the cluster configuration

2023-12-05 11:34 UTC, breskeby approved these changes

2023-12-05 12:44 UTC, alex-spies commented
Thanks @breskeby for the quick review!

2023-12-05 12:51 UTC, alex-spies commented
Oh no, the PR was opened against my fork :facepalm: 

Re-opening here: https://github.com/elastic/elasticsearch/pull/102979

2023-12-05 12:51 UTC, closed without merging